import type { Metadata } from "next";
import "./globals.css";
import { Footer } from "@/components/ui/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full antialiased">
      <body className="min-h-full flex flex-col">
        {" "}
        <main className="min-h-screen bg-[#f4f1e8]">
          {children}
          <Footer />
        </main>
      </body>
    </html>
  );
}
